import fs from "fs/promises";
import path from "path";

export interface BundleResult {
  manifest: Record<string, string>;
  fileEntries: Array<{
    path: string;
    hash: string;
    content: string;
    base64Content: string;
    type: string;
    size: number;
  }>;
}

export class Bundler {
  static async createBundle(config: any): Promise<BundleResult> {
    const pages = config.pages || [];
    const branding = config.branding || {};
    const primaryColor = branding.colors?.primary || "#2563eb";
    const siteName = branding.name || "Shpitto Site";

    const files: Array<{ path: string; content: string; type: string }> = [];

    for (const page of pages) {
      const pagePath = page.path === "/" ? "/index.html" : `${page.path.replace(/^\//, "")}/index.html`;
      const pageTitle = page.seo?.title || `${siteName} - ${page.path}`;
      const pageDesc = page.seo?.description || "A professional website generated by Shpitto.";
      
      const content = page.puckData?.content || [];
      const bodyHtml = content.map((component: any) => this.renderComponent(component, branding)).join("\n");
      const seoSchema = typeof page.puckData?.root?.props?.seoSchema === "string" ? page.puckData.root.props.seoSchema : "";
      const seoSchemaSafe = seoSchema ? seoSchema.replace(/</g, "\\u003c") : "";
      const seoSchemaTag = seoSchemaSafe ? `<script type="application/ld+json">${seoSchemaSafe}</script>` : "";

      const navLinks = pages.map((p: any) => ({
        label: p.seo?.title?.split("|")[0].trim() || (p.path === "/" ? "Home" : p.path.replace("/", "")),
        url: p.path === "/" ? "/index.html" : `/${p.path.replace(/^\//, "")}/index.html`
      })).slice(0, 5);

      const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${pageTitle}</title>
    <meta name="description" content="${pageDesc}">
    ${seoSchemaTag}
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: '${primaryColor}',
                    }
                }
            }
        }
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        body { font-family: 'Inter', sans-serif; }
    </style>
</head>
<body class="bg-white text-slate-900">
    <header class="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-200/60 shadow-sm">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <a href="/index.html" class="flex items-center gap-3 hover:opacity-80 transition-opacity">
                    ${branding.logo ? `<img src="${branding.logo}" alt="${siteName} Logo" class="h-10 w-auto">` : `<div class="w-10 h-10 bg-primary rounded-xl flex items-center justify-center text-white font-bold text-xl shadow-lg shadow-primary/30">${siteName[0]}</div>`}
                    <span class="font-bold text-xl tracking-tight text-slate-900">${siteName}</span>
                </a>
            </div>
            <nav class="hidden md:flex items-center gap-6">
                ${navLinks.map((link: any) => {
                    const isActive = link.url === (page.path === "/" ? "/index.html" : `/${page.path.replace(/^\//, "")}/index.html`);
                    const activeClass = "text-primary font-bold";
                    const inactiveClass = "text-slate-600 hover:text-primary";
                    return `<a href="${link.url}" class="text-sm font-semibold transition-colors ${isActive ? activeClass : inactiveClass}">${link.label}</a>`;
                }).join("")}
                <button class="bg-primary text-white px-5 py-2.5 rounded-full text-sm font-bold shadow-lg shadow-primary/25 hover:opacity-90 transition-all">Request Quote</button>
            </nav>
        </div>
    </header>

    <main>
        ${bodyHtml}
    </main>

    <footer class="bg-slate-950 text-white py-20">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="grid grid-cols-1 md:grid-cols-4 gap-12">
                <div class="col-span-1 md:col-span-2">
                    <div class="flex items-center gap-3 mb-6">
                        <div class="w-10 h-10 bg-primary rounded-xl flex items-center justify-center text-white font-bold text-xl">${siteName[0]}</div>
                        <span class="font-bold text-xl tracking-tight">${siteName}</span>
                    </div>
                    <p class="text-slate-400 max-w-sm mb-8">${pageDesc}</p>
                </div>
                <div>
                    <h4 class="font-bold mb-6">Navigation</h4>
                    <ul class="space-y-4 text-slate-400 text-sm">
                        ${navLinks.map((link: any) => `<li><a href="${link.url}" class="hover:text-primary transition-colors">${link.label}</a></li>`).join("")}
                    </ul>
                </div>
                <div>
                    <h4 class="font-bold mb-6">Connect</h4>
                    <ul class="space-y-4 text-slate-400 text-sm">
                        <li><a href="#" class="hover:text-primary transition-colors">LinkedIn</a></li>
                        <li><a href="#" class="hover:text-primary transition-colors">Twitter</a></li>
                    </ul>
                </div>
            </div>
            <div class="border-t border-slate-800 mt-20 pt-8 text-sm text-slate-500 flex justify-between">
                <p>&copy; ${new Date().getFullYear()} ${siteName}. All rights reserved.</p>
                <div class="flex gap-6">
                    <a href="#" class="hover:text-slate-300">Privacy Policy</a>
                    <a href="#" class="hover:text-slate-300">Terms of Service</a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>`;

      files.push({ path: page.path === "/" ? "/index.html" : `${page.path}/index.html`, content: fullHtml, type: "text/html" });
    }

    const manifest: Record<string, string> = {};
    const fileEntries: BundleResult["fileEntries"] = [];

    for (const file of files) {
        const crypto = await import("node:crypto");
        const buffer = Buffer.from(file.content);
        const base64Content = buffer.toString("base64");
        
        const hashInput = base64Content + file.path;
        const hash = crypto.createHash("md5").update(hashInput).digest("hex");
        
        manifest[file.path] = hash;
        fileEntries.push({ 
            path: file.path, 
            hash, 
            content: file.content,
            base64Content,
            type: file.type,
            size: buffer.length
        });
    }

    return { manifest, fileEntries };
  }

  private static renderComponent(component: any, branding: any): string {
    const { type, props } = component;
    const primaryColor = branding.colors?.primary || "#2563eb";

    switch (type) {
      case "Hero":
        const alignClass = props.align === "text-center" ? "text-center justify-center" : "text-left";
        const themeClass = props.theme === "dark" ? "bg-slate-950 text-white" : "bg-white text-slate-900";
        return `
        <section class="relative py-24 px-4 overflow-hidden ${themeClass} flex items-center min-h-[70vh]">
            <div class="container mx-auto relative z-10">
                <div class="max-w-3xl ${props.align === "text-center" ? "mx-auto" : ""}">
                    <h1 class="text-5xl md:text-7xl font-bold tracking-tight mb-6">${props.title}</h1>
                    ${props.description || props.subtitle ? `<p class="text-xl md:text-2xl mb-10 leading-relaxed text-slate-400">${props.description || props.subtitle}</p>` : ""}
                    <button class="bg-primary px-8 py-4 rounded-full font-bold shadow-lg shadow-primary/25 hover:opacity-90 transition-all">${props.ctaText || props.cta_text || "Learn More"}</button>
                </div>
            </div>
            ${props.effect === "retro-grid" ? `<div class="absolute inset-0 opacity-20" style="background-image: linear-gradient(to right, #334155 1px, transparent 1px), linear-gradient(to bottom, #334155 1px, transparent 1px); background-size: 40px 40px;"></div>` : ""}
        </section>`;

      case "Stats":
        return `
        <section class="py-20 bg-slate-50">
            <div class="container mx-auto px-4">
                <div class="grid grid-cols-2 md:grid-cols-4 gap-8">
                    ${(props.items || []).map((item: any) => `
                        <div class="text-center">
                            <div class="text-4xl font-bold text-primary mb-2">${item.value}</div>
                            <div class="text-slate-600 font-medium">${item.label}</div>
                        </div>
                    `).join("")}
                </div>
            </div>
        </section>`;

      case "ProductPreview":
      case "Product_Preview":
        return `
        <section class="py-24 bg-slate-50">
            <div class="container mx-auto px-4">
                <div class="text-center mb-16">
                    <h2 class="text-3xl md:text-5xl font-bold mb-6">${props.title || "Our Products"}</h2>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    ${(props.items || []).map((item: any) => `
                        <div class="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all group border border-slate-100">
                            <div class="aspect-video relative overflow-hidden bg-slate-100">
                                ${item.image ? `<img src="${item.image}" class="object-cover w-full h-full group-hover:scale-105 transition-transform duration-500" alt="${item.title}">` : ""}
                            </div>
                            <div class="p-8">
                                <div class="flex items-center justify-between gap-3 mb-3">
                                    <h3 class="text-xl font-bold">${item.title}</h3>
                                    ${item.tag ? `<span class="inline-flex items-center rounded-full bg-primary/10 text-primary px-3 py-1 text-xs font-bold">${item.tag}</span>` : ""}
                                </div>
                                <p class="text-slate-600 mb-6">${item.description}</p>
                            </div>
                        </div>
                    `).join("")}
                </div>
            </div>
        </section>`;

      case "FeatureHighlight":
      case "Feature_Highlight":
        const isRight = props.align === "right";
        return `
        <section class="py-24 bg-white overflow-hidden">
            <div class="container mx-auto px-4">
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                    <div class="${isRight ? 'lg:order-1' : ''}">
                        <h2 class="text-3xl md:text-5xl font-bold mb-6">${props.title}</h2>
                        <p class="text-lg text-slate-600 mb-8 leading-relaxed">${props.description}</p>
                        ${(props.features || []).length ? `
                        <div class="space-y-3 mb-10">
                          ${(props.features || []).map((f: any) => `
                            <div class="flex items-center gap-3">
                              <div class="w-5 h-5 bg-primary/10 text-primary rounded-full flex items-center justify-center">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                </svg>
                              </div>
                              <span class="font-medium text-slate-700">${f}</span>
                            </div>
                          `).join("")}
                        </div>
                        ` : ""}
                        ${(props.ctaText || props.cta_text) ? `
                        <a href="${props.ctaLink || props.cta_link || '#'}" class="inline-flex items-center justify-center px-8 py-4 bg-primary text-white rounded-full font-bold shadow-lg shadow-primary/25 hover:opacity-90 transition-all">
                            ${props.ctaText || props.cta_text}
                        </a>
                        ` : ""}
                    </div>
                    <div class="${isRight ? 'lg:order-2' : ''} relative">
                         ${props.image ? `<img src="${props.image}" class="rounded-3xl shadow-2xl relative z-10 w-full" alt="${props.title}">` : `<div class="aspect-square bg-slate-200 rounded-3xl animate-pulse"></div>`}
                    </div>
                </div>
            </div>
        </section>`;

      case "Content_Block":
        const alignContent = props.align === "center" ? "text-center mx-auto" : "text-left";
        return `
        <section class="py-24 bg-white">
            <div class="container mx-auto px-4">
                <div class="max-w-4xl ${alignContent}">
                    ${props.title ? `<h2 class="text-3xl md:text-4xl font-bold mb-8">${props.title}</h2>` : ""}
                    <div class="prose prose-lg prose-slate ${props.align === "center" ? "mx-auto" : ""} max-w-none">
                        ${props.content ? props.content.split('\n').map((line: string) => `<p>${line}</p>`).join('') : ""}
                    </div>
                </div>
            </div>
        </section>`;

      case "CTASection":
      case "CTA_Section":
        const ctaTheme = props.theme === "light" ? "bg-slate-50 text-slate-900" : props.theme === "dark" ? "bg-slate-950 text-white" : "bg-primary text-white";
        const btnTheme = props.theme === "light" ? "bg-primary text-white" : "bg-white text-slate-900";
        return `
        <section class="py-24 px-4 ${ctaTheme}">
            <div class="container mx-auto max-w-5xl text-center">
                <h2 class="text-4xl md:text-5xl font-bold mb-6">${props.title}</h2>
                ${props.description ? `<p class="text-xl md:text-2xl opacity-90 mb-10 max-w-2xl mx-auto">${props.description}</p>` : ""}
                <a href="${props.ctaLink || props.cta_link || '#'}" class="inline-block px-10 py-5 ${btnTheme} rounded-full font-bold text-lg shadow-xl hover:scale-105 transition-transform">
                    ${props.ctaText || props.cta_text || "Get Started"}
                </a>
            </div>
        </section>`;

      case "FAQ":
        return `
        <section class="py-24 bg-slate-50">
            <div class="container mx-auto px-4 max-w-3xl">
                ${props.title ? `<div class="text-center mb-16"><h2 class="text-3xl md:text-4xl font-bold">${props.title}</h2></div>` : ""}
                <div class="space-y-4">
                    ${(props.items || []).map((item: any, idx: number) => `
                        <div class="bg-white rounded-2xl p-8 shadow-sm border border-slate-100">
                            <h3 class="text-xl font-bold mb-3 text-slate-900">${item.question}</h3>
                            <p class="text-slate-600 leading-relaxed">${item.answer}</p>
                        </div>
                    `).join("")}
                </div>
            </div>
        </section>`;

      case "Logos":
        return `
        <section class="py-16 bg-white border-y border-slate-100">
            <div class="container mx-auto px-4">
                ${props.title ? `<p class="text-center text-sm font-semibold text-slate-500 uppercase tracking-wider mb-8">${props.title}</p>` : ""}
                <div class="flex flex-wrap justify-center items-center gap-12 md:gap-16 opacity-70 grayscale hover:grayscale-0 transition-all duration-500">
                    ${(props.items || []).map((item: any) => `
                        ${item.logo ? `<img src="${item.logo}" alt="${item.name}" class="h-8 md:h-10 w-auto object-contain">` : `<span class="font-bold text-xl text-slate-400">${item.name}</span>`}
                    `).join("")}
                </div>
            </div>
        </section>`;

      case "ValuePropositions":
      case "Value_Propositions":
        return `
        <section class="py-24 bg-white">
            <div class="container mx-auto px-4">
                <div class="text-center mb-16">
                    <h2 class="text-3xl md:text-4xl font-bold mb-4">${props.title || "Why Choose Us"}</h2>
                    <p class="text-slate-600 max-w-2xl mx-auto">${props.subtitle || ""}</p>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                    ${(props.items || []).map((item: any) => `
                        <div class="p-8 rounded-2xl border border-slate-100 hover:shadow-xl transition-all group">
                            <div class="w-12 h-12 bg-blue-50 text-primary rounded-xl flex items-center justify-center mb-6 group-hover:bg-primary group-hover:text-white transition-colors">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                </svg>
                            </div>
                            <h3 class="text-xl font-bold mb-4">${item.title}</h3>
                            <p class="text-slate-600">${item.description}</p>
                        </div>
                    `).join("")}
                </div>
            </div>
        </section>`;

      case "Testimonials":
        return `
        <section class="py-24 bg-white overflow-hidden">
            <div class="container mx-auto px-4">
                <div class="text-center mb-16">
                    <h2 class="text-3xl md:text-4xl font-bold mb-4">${props.title || "Client Stories"}</h2>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                    ${(props.items || []).map((item: any) => `
                        <div class="p-8 rounded-2xl bg-slate-50 border border-slate-100">
                            <p class="text-lg text-slate-700 italic mb-8">"${item.content}"</p>
                            <div class="flex items-center gap-4">
                                <div>
                                    <div class="font-bold">${item.author}</div>
                                    <div class="text-sm text-slate-500">${item.role || ""}</div>
                                </div>
                            </div>
                        </div>
                    `).join("")}
                </div>
            </div>
        </section>`;

      default:
        return `<section class="py-10 text-center text-slate-400">Component ${type} not yet implemented for static export</section>`;
    }
  }
}
