export const routes = [
  '/',
  '/pricing',
  '/flux-prompt-generator',
  '/sign-in',
  '/admin',
  '/admin/tasks',
  '/admin/projects',
  '/admin/assets',
  '/admin/gift-codes',
  '/admin/settings',
  '/admin/users',
  '/app',
  '/app/generate',
  '/app/history',
  '/app/giftcode',
  '/app/order',
  '/privacy-policy',
  '/terms-of-use',
] as const;
