export function renderWebsiteQualityContract(): string {
  return [
    "## Website Quality Contract",
    "- Runtime scope is website generation only; do not generate mobile apps, slide decks, native app screens, or external coding-agent instructions.",
    "- One generated website must render correctly in desktop browser, MacBook, iPad, iPhone, and Android preview shells.",
    "- Treat preview as WYSIWYG: navigation, layout, media, forms, and responsive breakpoints must work inside iframe preview.",
    "- Use the selected local design system as the visual source of truth for color, typography, spacing, radius, shadows, motion, and component rhythm.",
    "- Avoid AI-slop defaults: no placeholder copy, no generic Feature 1/2/3 grids, no anonymous testimonials, no fake metrics, no repeated card modules across pages.",
    "- Navigation must use meaningful route labels; do not leave desktop or mobile nav shells as generic menu/navigation/quick links scaffolds.",
    "- Navigation and footer must not expose undeclared internal routes; every visitor-facing site link in the shared shell must belong to the confirmed route plan unless it is an approved external destination or asset.",
    "- Footer must contribute real site content; avoid copyright-only placeholders, label-only footers, or generic legal shells that add no value.",
    "- Footer must use a structured shell with a distinct footer band plus separate identity, navigation, and support/meta zones when the shared CSS defines footer-shell utilities; do not collapse the footer into a flat row of links.",
    "- Mobile nav may collapse visually, but it still needs the same meaningful destinations as desktop rather than a menu-only placeholder shell.",
    "- Homepage first screen must identify the brand, object, institution, person, product, or business category before broad value propositions; the first viewport must not read as an interchangeable SaaS or agency template.",
    "- Every route must include concrete nouns from the confirmed brief, uploaded/domain/source material, selected surface mode, or route role. Do not rely on abstract filler such as solutions, innovation, excellence, seamless, powerful, or future-ready without subject-specific details.",
    "- Page archetypes must stay distinct: home establishes identity and visitor path, products/catalog supports comparison, solutions/services explains process or scenario fit, cases/proof shows evidence, about builds trust, contact clarifies conversion expectations, docs/reference supports wayfinding, content hubs organize resources, and blogs/editorial surfaces foreground writing.",
    "- CTA labels must describe the route-specific next action. Do not repeat generic labels such as Learn More, Get Started, Read More, or Submit as the dominant action system across the site.",
    "- Mobile composition must be readable without text collisions: headings, CTA groups, cards, stats, and nav labels must fit their containers and must not push the first meaningful content below decorative empty space.",
    "- When refine or generation creates a new page, that page must reuse the current site's active theme and the same shared navigation/footer shell unless the brief explicitly requests a shell redesign.",
    "- External imagery must come from source-backed or project-owned assets; do not ship example.com, placeholder.com, or other demo/stock placeholder URLs.",
    "- Public contact details and outbound URLs must be publishable; do not ship reserved placeholder domains such as `.example`, `.test`, `.invalid`, `localhost`, or `example.com` in visible copy or href/src attributes.",
    "- Metrics must be source-backed; do not invent percentages, multipliers, \"hours saved\", growth, or conversion-lift claims without brief or citation support.",
    "- Visual direction must be distinctive: expressive type pairing, intentional background system, layered sections, strong hero composition, and mobile-specific composition.",
    "- CSS must include responsive strategy using media queries, container queries, or clamp-based fluid sizing.",
    "- Typography safety: keep generated UI text at non-negative letter-spacing by default. Use `letter-spacing: 0` for body text, headings, buttons, and links unless a small uppercase label explicitly needs positive tracking.",
    "- CSS color discipline: raw hex colors are allowed only inside the `:root` token block. Outside `:root`, use `var(...)`, `rgba(...)`, or `color-mix(...)` from tokens; do not put hex fallbacks inside component selectors.",
    "- Every page must contain enough route-specific content depth to stand alone; sibling pages must not be superficial copies.",
    "- When the workflow explicitly requires Blog detail pages, each detail route must be a complete publishable article with a real body, meaningful section structure, and enough route-specific substance to read as finished content rather than a shell, stub, or metadata-only placeholder.",
    "- Route / must always read as the official homepage and institutional overview, not as a downloads hub, certification portal, or login page.",
    "- If a hero visual rail is tall, it must contain real media, chart, or data-viz content; do not leave a large empty visual card with only bottom-aligned text.",
    "- Result cards rendered inside a 12-column grid must span the full available row unless the design explicitly calls for a narrower card layout.",
    "- Final HTML must include viewport meta, semantic landmarks, accessible labels, keyboard-safe interactions, and shared stylesheet/script references.",
  ].join("\n");
}
